apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp 
  template:
    metadata:
      labels:
        app: gcp 
    spec: 
      containers:
      - name: gcp-devops-gke
        image: gcr.io/cicd-pipeline-tracker/expensetracker:latest
        ports:
        - containerPort: 80
        env:
          - name: PORT 
            value: "80"
---
apiVersion: "v1"
kind: Service
metadata:
  name: "gcp-devops-gke-service"
  namespace: "gcp-devops-dev"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "gcp" 
  type: "LoadBalancer"